services:
  - type: web
    name: chordsnip-api
    env: python
    buildCommand: |
      pip install Cython
      pip install numpy==1.23.5
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8080


